name: workflows

on:
  - push
  - pull_request

jobs:

  test:
    name: ${{ matrix.os }}-ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - macos-11.0
        ghc:
          - 8.10.3
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0

      - name: test
        run: |
          cabal v2-build all
